### ISSUE TITLE
model export where input/output shape is user requested

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/hermes#36]
The forward call at inference time for the PE project will look something like this:

```python
def forward(self, n_samples: int, context: torch.Tensor):
    return self.flow.sample(n_samples, context)
```
Where `n_samples` are drawn from a (likely standard normal) distribution, and run through a normalizing flow conditioned on the context to produce posterior samples. This is tied to the API of the nflows package. 

A couple of questions:
1. Is it even possible to export a model where the shape of the output (i.e. the number of samples) is not predetermined, and requested by the user? 

3. If so, I think [this](https://github.com/ML4GW/hermes/blob/main/hermes/hermes.quiver/hermes/quiver/exporters/torch_onnx.py#L39) TODO will need to be addressed (at least for onnx exports), since `n_samples` must be a positive integer. Happy to pick this up. It looks like the TODO referenced adjusting [this](https://github.com/ML4GW/hermes/blob/main/hermes/hermes.quiver/hermes/quiver/exporters/exporter.py#L182) argument to also take user provided tensors, but wanted to clarify before going after it.

**Comment by alecgunny** [comment]
1. For this to be supported as an ONNX graph, `n_samples` would need to be allowed to be a torch tensor. Can whatever `flow.sample` does be made amenable to accepting a `(1,)`-shaped scalar `Tensor`? If so, this should be supported, you'll just probably have to manually update `model.config.output[0].dim[0]` to be `-1` after export then re-saving the config.
2. In either case, yes that will definitely need to be updated.

A couple potentially hackier options for support here, but that I think would be able to work right now, are
1. Hard-code `n_samples` into the ONNX graph. Not sure exactly what the inference use case looks like here, but if you don't need a lot of flexibility (or your sampling mechanism can't operate on `Tensor`s) this will certainly simplify things.
2. If you do need the flexibility and your sampling mechanism can accept a `Tensor`, wrap the model so that rather than accepting an `n_samples` argument, you just accept a dummy tensor and use its length as `n_samples`
