### ISSUE TITLE
Ensure that the correct GPU is being used

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/hermes#39]
Sorry for the vague title - not sure what the root of the issue is/how this is going to get fixed. We just need to make sure that an enterprise-level GPU is being used for export, and that the same GPU is used for inference.

**Comment by alecgunny** [comment]
I don't know that it's `hermes` job to coordinate which GPUs get used between export and inference: this is strictly a TRT limitation and is probably best left to downstream applications to do that coordination. The issue which we're running into here is just that we'd like:
1. `hermes.aeriel.serve.serve` to accept full-blown GPU UUIDs to its `gpus` argument
2. If we pass regular indices to `gpus`, we'd like them to match the IDs found in `nvidia-smi`, since that will be the source most people use to find out which GPUs they have and which ones they would like to use. This can be organized by iterating through the GPUs listed in `/proc/driver/nvidia/gpus/`, then matching indices to the value found in the `Device Minor` field of each directory's `information` file.

**Comment by alecgunny** [comment]
Interesting, these might be related. Couple follow up questions:
1. Can you give an example of a value of `gpus=` you gave, the corresponding setting of `CUDA_VISIBLE_DEVICES`, and which devices ended up getting used? How do you infer which devices triton ultimately uses: by inspecting the server logs or looking at `nvidia-smi` and seeing which GPUs are being used the triton process?
2. When you say "it will say that `None` value was given," what do you mean exactly? I don't think hermes logs that information anywhere
