### ISSUE TITLE
Tagged release of Hermes packages

### ISSUE THREAD

**Issue by duncanmmacleod** [ML4GW/hermes#52]
Is it possible to tag a release of this project, to support building packages (conda?) for the Hermes libraries, in turn to support use of Hermes in a LIGO search pipeline?

@vasskliris is currently using Hermes from 12e19f1 in support of the MLy burst search pipeline, so that would be an ideal target for a 0.1.0 (or similar) tag.

**Comment by EthanMarx** [comment]
Hi Duncan, yes we can (and should already have been) doing this. For our own projects we've been mostly adding `hermes` as a submodule for quick iteration. I think Vassilis is currently the only other user who has adopted, so there hasn't been huge pressure to version responsibly. 

I'll tag that commit Vassilis is using as `0.1.0` and we can go from there.

**Comment by duncanmmacleod** [comment]
Thanks @EthanMarx, that would be very helpful.

For the record, my plan was to attempt to create some conda packages directly from the github archive tarball, please let me know if you object. I'll definitely ask you to review the layout before I push up to conda-forge.

**Comment by EthanMarx** [comment]
@duncanmmacleod @VasSkliris `hermes` is now pip installable as a single package via `pip install ml4gw-hermes`. 
Despite the PyPI package name change (due to conflict) all of the imports Vassili uses in [this](https://git.ligo.org/mly/mly_pipeline/-/blob/master/mly_pipeline/continuous_FAR.py) script he pointed me to should work as is:

```python
from hermes import quiver as qv
from hermes.aeriel.client import InferenceClient
from hermes.aeriel.serve import serve
```

Unfortunately, the version `0.0.1` just uploaded to PyPI is not the _exact_ commit referenced above that Vassili is using. However, all the commits since then have mostly been CI fixes / repository management changes. None of the functionality used in `mly` should have been changed at all. 

Still, I would recommend doing some tests to ensure everything runs as expected before adding this into a production environment. If anything goes wrong please file an issue / reach out to me.

**Comment by duncanmmacleod** [comment]
Thanks @EthanMarx.

@VasSkliris, please confirm that this works for you.

**Comment by EthanMarx** [comment]
@VasSkliris closing as I haven't heard from you in some time. Feel free to re open if there are any problems
